function game = process_data(str)
%PROCESS_DATA process a txt file with data about the multiplayer game

fileID = fopen(str,'r');

% First, we scan the first line to learn the roles of both players
C = textscan(fileID,...
    '%s %s %s %s', 1,...
    'Delimiter', {':', ','});
joueur1 = C{2}{1};
joueur2 = C{4}{1};

% We add the role fields to our structure
game.robot1 = joueur1;
game.robot2 = joueur2;

% Then, we scan the rest of the file
C = textscan(fileID,...
    '%d %s %d %f %s %d %d %s %f %f %f %d %d %d %s %s %d %d %s %f %f %f %d %d %d %s %s',...
    'Delimiter', ';', 'CommentStyle', '#');

fclose(fileID);

% And we put the data into a table, itself into a field of our structure
game.data = table(C{1},C{2},C{3},C{4},C{5}, C{6},C{7},C{8},C{9},...
    C{10},C{11},C{12},C{13},C{14},C{15},C{16}, C{17},C{18},C{19},C{20},...
    C{21},C{22},C{23},C{24},C{25},C{26},C{27},...
    'VariableNames',...
    {'time' 'treesState' 'scoreGlobal' 'waterTank' 'leaks' 'score1' ...
    'autonomous1' 'alarms1' 'x1' 'y1' 'theta1' ...
    'energy1' 'temp1' 'water1' 'shortKeys1' 'clicks1' ...
    'score2' 'autonomous2' 'alarms2' 'x2' 'y2' ...
    'theta2' 'energy2' 'temp2' 'water2' 'shortKeys2' ...
    'clicks2'});

end